/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preseve that abilty, always export from Quest to regenerate this file.
 *   To setup props, bindings and actions, use the Quest editor
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import { styled } from '@mui/material/styles';

const CardGift1 = styled('div')(({ theme }) => ({
  backgroundColor: `rgba(255, 255, 255, 1)`,
  boxShadow: `0px 4px 16px rgba(34, 65, 58, 0.16)`,
  borderRadius: `12px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `24px 20px`,
  boxSizing: `border-box`,
  overflow: `hidden`,
  height: 'auto',
  width: 'fit-content',
}));

const Group96 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  height: `52px`,
  width: `217px`,
  margin: `0px`,
});

const GetFree1Totebag = styled('div')(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(34, 65, 58, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `500`,
  fontSize: `20px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `capitalize`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
}));

const CanBeTakenFromOurOff = styled('div')(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(112, 138, 132, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `400`,
  fontSize: `12px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `capitalize`,
  position: `absolute`,
  left: `0px`,
  top: `34px`,
}));

const Button1 = styled('div')(({ theme }) => ({
  backgroundColor: `rgba(1, 152, 117, 1)`,
  borderRadius: `12px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `center`,
  alignItems: `center`,
  padding: `8px 16px`,
  boxSizing: `border-box`,
  margin: `24px 0px 0px 0px`,
  overflow: `hidden`,
}));

const JoinNow = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `500`,
  fontSize: `14px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `capitalize`,
  margin: `0px`,
});

function CardGift(props) {
  return (
    <CardGift1 className={props.className}>
      <Group96>
        <GetFree1Totebag>{`Get a 3d filament`}</GetFree1Totebag>
        <CanBeTakenFromOurOff>
          {`Can be taken from our offcial store`}
        </CanBeTakenFromOurOff>
      </Group96>
      <Button1>
        <JoinNow>{`Claim Now`}</JoinNow>
      </Button1>
    </CardGift1>
  );
}

export default CardGift;
