/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preseve that abilty, always export from Quest to regenerate this file.
 *   To setup props, bindings and actions, use the Quest editor
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from "react";
import MaskGroupImage from "./../assets/images/CardEvent_Mask_group.png";
import CombinedShapeImage from "./../assets/images/CardEvent_Combined_Shape.png";
import VectorImage from "./../assets/images/CardEvent_Vector.png";
import { styled } from "@mui/material/styles";

const CardEvent1 = styled("div")(({ theme }) => ({
  backgroundColor: `rgba(255, 255, 255, 1)`,
  boxShadow: `0px 4px 16px rgba(34, 65, 58, 0.16)`,
  borderRadius: `12px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `20px`,
  boxSizing: `border-box`,
  overflow: `hidden`,
  height: "auto",
  width: "520px"
}));

const MaskGroup = styled("img")({
  height: `213px`,
  width: `177px`,
  margin: `0px`
});

const Group95 = styled("div")({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `100%`,
  height: `213px`,
  margin: `0px 0px 0px 32px`
});

const CareForWasteYourFirs = styled("div")(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(34, 65, 58, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `600`,
  fontSize: `20px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `232px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`
}));

const Frame1389 = styled("div")({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  left: `0px`,
  top: `176px`
});

const Button1 = styled("div")(({ theme }) => ({
  backgroundColor: `rgba(1, 152, 117, 1)`,
  borderRadius: `12px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `center`,
  alignItems: `center`,
  padding: `8px 16px`,
  boxSizing: `border-box`,
  margin: `0px`,
  overflow: `hidden`
}));

const JoinNow = styled("div")({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `500`,
  fontSize: `14px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `capitalize`,
  margin: `0px`
});

const ButtonOutline = styled("div")({
  border: `1px solid rgba(1, 152, 117, 1)`,
  boxSizing: `border-box`,
  borderRadius: `12px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `center`,
  alignItems: `center`,
  padding: `8px 16px`,
  margin: `0px 0px 0px 39px`,
  overflow: `hidden`
});

const SeeMore = styled("div")(({ theme }) => ({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(1, 152, 117, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `500`,
  fontSize: `14px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `capitalize`,
  margin: `0px`
}));

const Frame1388 = styled("div")({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  paddingTop: `16px`,
  boxSizing: `border-box`,
  left: `0px`,
  top: `88px`
});

const Group93 = styled("div")({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `160px`,
  height: `24px`,
  margin: `0px`
});

const DepokJawaBarat = styled("div")(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(112, 138, 132, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `400`,
  fontSize: `12px`,
  letterSpacing: `-0.30000001192092896px`,
  textDecoration: `none`,
  lineHeight: `16px`,
  textTransform: `none`,
  position: `absolute`,
  left: `32px`,
  top: `4px`
}));

const IconLocation = styled("div")({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `24px`,
  height: `24px`,
  left: `0px`,
  top: `0px`
});

const CombinedShape = styled("img")({
  height: `21.18px`,
  width: `15px`,
  position: `absolute`,
  left: `4px`,
  top: `1px`
});

const Group94 = styled("div")({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `70px`,
  height: `24px`,
  margin: `0px 0px 0px 32px`
});

const Q88100 = styled("div")({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(112, 138, 132, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `400`,
  fontSize: `12px`,
  letterSpacing: `-0.30000001192092896px`,
  textDecoration: `none`,
  lineHeight: `16px`,
  textTransform: `none`,
  position: `absolute`,
  left: `32px`,
  top: `4px`
});

const Users = styled("div")({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `24px`,
  height: `24px`,
  left: `0px`,
  top: `0px`,
  overflow: `hidden`
});

const Vector = styled("img")({
  height: `16.8px`,
  width: `21.6px`,
  position: `absolute`,
  left: `1px`,
  top: `4px`
});

function CardEvent(props) {
  return (
    <CardEvent1 className={props.className}>
      <MaskGroup src={MaskGroupImage} loading="lazy" alt={"Mask group"} />
      <Group95>
        <CareForWasteYourFirs>
          {`Care for Waste: Your first step to care about the waste around you`}
        </CareForWasteYourFirs>
        <Frame1389>
          <Button1>
            <JoinNow>{`Join Now`}</JoinNow>
          </Button1>
          <ButtonOutline>
            <SeeMore>{`See More`}</SeeMore>
          </ButtonOutline>
        </Frame1389>
        <Frame1388>
          <Group93>
            <DepokJawaBarat>{`Depok, Jawa Barat`}</DepokJawaBarat>
            <IconLocation>
              <CombinedShape
                src={CombinedShapeImage}
                loading="lazy"
                alt={"Combined Shape"}
              />
            </IconLocation>
          </Group93>
          <Group94>
            <Q88100>{`88/100`}</Q88100>
            <Users>
              <Vector src={VectorImage} loading="lazy" alt={"Vector"} />
            </Users>
          </Group94>
        </Frame1388>
      </Group95>
    </CardEvent1>
  );
}

export default CardEvent;
