/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preseve that abilty, always export from Quest to regenerate this file.
 *   To setup props, bindings and actions, use the Quest editor
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from "react";
import Image1Image from "./../assets/images/Gopay_image_1.png";
import { styled } from "@mui/material/styles";

const Gopay1 = styled("div")({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  width: "100%",
  height: `76px`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`
});

const Rectangle696 = styled("div")({
  backgroundColor: `rgba(255, 255, 255, 1)`,
  border: `1px solid rgba(0, 0, 0, 1)`,
  boxSizing: `border-box`,
  borderRadius: `12px`,
  width: `144px`,
  height: `76px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`
});

const Image1 = styled("img")({
  height: `76px`,
  width: `111.82px`,
  objectFit: `cover`,
  position: `absolute`,
  left: `16px`,
  top: `0px`
});

function Gopay(props) {
  return (
    <Gopay1 className={props.className}>
      <Rectangle696></Rectangle696>
      <Image1 src={Image1Image} loading="lazy" alt={"image 1"} />
    </Gopay1>
  );
}

export default Gopay;
