/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preseve that abilty, always export from Quest to regenerate this file.
 *   To setup props, bindings and actions, use the Quest editor
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from "react";
import Image2Image from "./../assets/images/Ovo_image_2.png";
import { styled } from "@mui/material/styles";

const Ovo1 = styled("div")({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  width: "100%",
  height: `76px`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`
});

const Rectangle697 = styled("div")({
  backgroundColor: `rgba(76, 51, 149, 1)`,
  borderRadius: `12px`,
  width: `144px`,
  height: `76px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`
});

const Image2 = styled("img")({
  height: `76px`,
  width: `124.72px`,
  objectFit: `cover`,
  position: `absolute`,
  left: `10px`,
  top: `0px`
});

function Ovo(props) {
  return (
    <Ovo1 className={props.className}>
      <Rectangle697></Rectangle697>
      <Image2 src={Image2Image} loading="lazy" alt={"image 2"} />
    </Ovo1>
  );
}

export default Ovo;
