/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preseve that abilty, always export from Quest to regenerate this file.
 *   To setup props, bindings and actions, use the Quest editor
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from "react";
import VectorImage from "./../assets/images/qrcode.svg";
import { styled } from "@mui/material/styles";

const ServiceButton1 = styled("div")({
  border: `3px solid rgba(1, 152, 117, 1)`,
  boxSizing: `border-box`,
  borderRadius: `12px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  width: "100%",
  justifyContent: `space-between`,
  alignItems: `center`,
  padding: `24px 32px`,
  overflow: `hidden`,
  height: "auto"
});

const PlusCircle = styled("div")({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `64px`,
  height: `64px`,
  overflow: `hidden`,
  borderRadius: `100%`,
  backgroundColor: `#019875`
});

const Vector = styled("img")({
  height: `38px`,
  width: `38px`,
  position: `absolute`,
  left: `50%`,
  top: `50%`,
  transform: `translate(-50%, -50%)`
});

const SortYourTrashGiveItT = styled("div")(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(1, 152, 117, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `600`,
  fontSize: `16px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`
}));

function ServiceButton(props) {
  return (
    <ServiceButton1 className={props.className}>
      <PlusCircle>
        <Vector src={VectorImage} loading="lazy" alt={"Vector"} />
      </PlusCircle>
      <SortYourTrashGiveItT>
        {`Scan the barcode, 
Put the trash in,
Then earn points!`}
      </SortYourTrashGiveItT>
    </ServiceButton1>
  );
}

export default ServiceButton;
