/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preseve that abilty, always export from Quest to regenerate this file.
 *   To setup props, bindings and actions, use the Quest editor
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from "react";
import Image4Image from "./../assets/images/Shopeepay_image_4.png";
import { styled } from "@mui/material/styles";

const Shopeepay1 = styled("div")({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  width: "100%",
  height: `76px`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`
});

const Image4 = styled("img")({
  height: `76px`,
  width: `145.54px`,
  objectFit: `cover`,
  position: `absolute`,
  left: `-1px`,
  top: `0px`
});

function Shopeepay(props) {
  return (
    <div style={{ borderRadius: "12px", overflow: "hidden", width: "144px" }}>
      <Shopeepay1 className={props.className}>
        <Image4 src={Image4Image} loading="lazy" alt={"image 4"} />
      </Shopeepay1>
    </div>
  );
}

export default Shopeepay;
