/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preseve that abilty, always export from Quest to regenerate this file.
 *   To setup props, bindings and actions, use the Quest editor
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from "react";
import Ellipse63Image from "./../assets/images/Timeline_Ellipse_63.png";
import Rectangle693Image from "./../assets/images/Timeline_Rectangle_693.png";
import Rectangle694Image from "./../assets/images/Timeline_Rectangle_694.png";
import Rectangle695Image from "./../assets/images/Timeline_Rectangle_695.png";
import Ellipse631Image from "./../assets/images/Timeline_Ellipse_63_1.png";
import Ellipse632Image from "./../assets/images/Timeline_Ellipse_63_2.png";
import Ellipse633Image from "./../assets/images/Timeline_Ellipse_63_3.png";
import Ellipse634Image from "./../assets/images/Timeline_Ellipse_63_4.png";
import { styled } from "@mui/material/styles";

const Timeline1 = styled("div")({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  width: "100%",
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  overflow: `hidden`,
  height: "auto"
});

const ShippingInformation = styled("div")({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  margin: `0px`
});

const Timestamp = styled("div")({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-end`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `40px`,
  margin: `0px`,
  overflow: `hidden`
});

const Q0320 = styled("div")(({ theme }) => ({
  width: `38px`,
  textAlign: `right`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(34, 65, 58, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `400`,
  fontSize: `12px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  margin: `0px`
}));

const Q1030 = styled("div")(({ theme }) => ({
  textAlign: `right`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(150, 198, 187, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `400`,
  fontSize: `10px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  margin: `0px`
}));

const Line = styled("div")({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  width: `4px`,
  margin: `0px 0px 0px 16px`
});

const Rectangle688 = styled("div")(({ theme }) => ({
  backgroundColor: `rgba(1, 152, 117, 1)`,
  width: `0.5px`,
  height: `59px`,
  position: `absolute`,
  left: `2px`,
  top: `19px`
}));

const Frame1373 = styled("div")({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `4px`,
  height: `4px`,
  left: `0px`,
  top: `7px`
});

const Ellipse63 = styled("img")({
  height: `16px`,
  width: `16px`,
  position: `absolute`,
  left: `-6px`,
  top: `-6px`
});

const Frame1398 = styled("div")({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `8px`,
  height: `8px`,
  left: `-2px`,
  top: `-2px`
});

const Group116 = styled("div")({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `8px`,
  height: `8px`,
  left: `0px`,
  top: `0px`
});

const Rectangle693 = styled("img")({
  height: `4.67px`,
  width: `8px`,
  position: `absolute`,
  left: `0px`,
  top: `3px`
});

const Rectangle694 = styled("img")({
  height: `2.67px`,
  width: `3.67px`,
  position: `absolute`,
  left: `0px`,
  top: `3px`
});

const Rectangle695 = styled("img")({
  height: `2.67px`,
  width: `3.67px`,
  position: `absolute`,
  left: `12px`,
  top: `5px`
});

const Info = styled("div")({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px 0px 24px 0px`,
  boxSizing: `border-box`,
  flex: `1`,
  margin: `0px 0px 0px 16px`,
  overflow: `hidden`
});

const SeeYourRequest = styled("div")(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(34, 65, 58, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `500`,
  fontSize: `14px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  alignSelf: `stretch`,
  margin: `0px`
}));

const YourRequestedIsBeing = styled("div")(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(150, 198, 187, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `400`,
  fontSize: `12px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  alignSelf: `stretch`,
  margin: `6px 0px 0px 0px`
}));

const ShippingInformation1 = styled("div")({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  margin: `4px 0px 0px 0px`
});

const Timestamp1 = styled("div")({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-end`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `40px`,
  margin: `0px`,
  overflow: `hidden`
});

const Q03201 = styled("div")(({ theme }) => ({
  width: `38px`,
  textAlign: `right`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(34, 65, 58, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `400`,
  fontSize: `12px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  margin: `0px`
}));

const Q1031 = styled("div")(({ theme }) => ({
  textAlign: `right`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(150, 198, 187, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `400`,
  fontSize: `10px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  margin: `0px`
}));

const Line1 = styled("div")({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  width: `4px`,
  margin: `0px 0px 0px 16px`
});

const Frame1372 = styled("div")({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `4px`,
  height: `4px`,
  left: `0px`,
  top: `7px`
});

const Ellipse631 = styled("img")({
  height: `4px`,
  width: `4px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`
});

const Rectangle6881 = styled("div")(({ theme }) => ({
  backgroundColor: `rgba(1, 152, 117, 1)`,
  width: `0.5px`,
  height: `65px`,
  position: `absolute`,
  left: `2px`,
  top: `13px`
}));

const Info1 = styled("div")({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px 0px 24px 0px`,
  boxSizing: `border-box`,
  flex: `1`,
  margin: `0px 0px 0px 16px`,
  overflow: `hidden`
});

const Received = styled("div")(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(34, 65, 58, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `500`,
  fontSize: `14px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  alignSelf: `stretch`,
  margin: `0px`
}));

const YourRequestHasBeenRe = styled("div")(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(150, 198, 187, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `400`,
  fontSize: `12px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  alignSelf: `stretch`,
  margin: `6px 0px 0px 0px`
}));

const ShippingInformation2 = styled("div")({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  margin: `4px 0px 0px 0px`
});

const Timestamp2 = styled("div")({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-end`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `40px`,
  margin: `0px`,
  overflow: `hidden`
});

const Q03202 = styled("div")(({ theme }) => ({
  width: `38px`,
  textAlign: `right`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(34, 65, 58, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `400`,
  fontSize: `12px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  margin: `0px`
}));

const Q1033 = styled("div")(({ theme }) => ({
  textAlign: `right`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(150, 198, 187, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `400`,
  fontSize: `10px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  margin: `0px`
}));

const Line2 = styled("div")({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  width: `4px`,
  margin: `0px 0px 0px 16px`
});

const Frame13721 = styled("div")({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `4px`,
  height: `4px`,
  left: `0px`,
  top: `7px`
});

const Ellipse632 = styled("img")({
  height: `4px`,
  width: `4px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`
});

const Rectangle6882 = styled("div")(({ theme }) => ({
  backgroundColor: `rgba(1, 152, 117, 1)`,
  width: `0.5px`,
  height: `65px`,
  position: `absolute`,
  left: `2px`,
  top: `13px`
}));

const Info2 = styled("div")({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px 0px 24px 0px`,
  boxSizing: `border-box`,
  flex: `1`,
  margin: `0px 0px 0px 16px`,
  overflow: `hidden`
});

const OnTheWay = styled("div")(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(34, 65, 58, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `500`,
  fontSize: `14px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  alignSelf: `stretch`,
  margin: `0px`
}));

const WeAreOnOurWayToYourP = styled("div")(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(150, 198, 187, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `400`,
  fontSize: `12px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  alignSelf: `stretch`,
  margin: `6px 0px 0px 0px`
}));

const ShippingInformation3 = styled("div")({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  margin: `4px 0px 0px 0px`
});

const Timestamp3 = styled("div")({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-end`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `40px`,
  margin: `0px`,
  overflow: `hidden`
});

const Q03203 = styled("div")(({ theme }) => ({
  width: `38px`,
  textAlign: `right`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(34, 65, 58, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `400`,
  fontSize: `12px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  margin: `0px`
}));

const Q1044 = styled("div")(({ theme }) => ({
  textAlign: `right`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(150, 198, 187, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `400`,
  fontSize: `10px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  margin: `0px`
}));

const Line3 = styled("div")({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  width: `4px`,
  margin: `0px 0px 0px 16px`
});

const Frame13722 = styled("div")({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `4px`,
  height: `4px`,
  left: `0px`,
  top: `7px`
});

const Ellipse633 = styled("img")({
  height: `4px`,
  width: `4px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`
});

const Rectangle6883 = styled("div")(({ theme }) => ({
  backgroundColor: `rgba(1, 152, 117, 1)`,
  width: `0.5px`,
  height: `65px`,
  position: `absolute`,
  left: `2px`,
  top: `13px`
}));

const Info3 = styled("div")({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px 0px 24px 0px`,
  boxSizing: `border-box`,
  flex: `1`,
  margin: `0px 0px 0px 16px`,
  overflow: `hidden`
});

const HasArrived = styled("div")(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(34, 65, 58, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `500`,
  fontSize: `14px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  alignSelf: `stretch`,
  margin: `0px`
}));

const WeHaveArrivedAtYourP = styled("div")(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(150, 198, 187, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `400`,
  fontSize: `12px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  alignSelf: `stretch`,
  margin: `6px 0px 0px 0px`
}));

const ShippingInformation4 = styled("div")({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  margin: `4px 0px 0px 0px`
});

const Timestamp4 = styled("div")({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-end`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `40px`,
  margin: `0px`,
  overflow: `hidden`
});

const Q03204 = styled("div")(({ theme }) => ({
  width: `38px`,
  textAlign: `right`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(34, 65, 58, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `400`,
  fontSize: `12px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  margin: `0px`
}));

const Q1117 = styled("div")(({ theme }) => ({
  textAlign: `right`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(150, 198, 187, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `400`,
  fontSize: `10px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  margin: `0px`
}));

const Line4 = styled("div")({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  width: `4px`,
  margin: `0px 0px 0px 16px`
});

const Frame13723 = styled("div")({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `4px`,
  height: `4px`,
  left: `0px`,
  top: `7px`
});

const Ellipse634 = styled("img")({
  height: `4px`,
  width: `4px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`
});

const Rectangle6884 = styled("div")({
  backgroundColor: `rgba(225, 227, 234, 1)`,
  width: `0.5px`,
  height: `65px`,
  position: `absolute`,
  left: `2px`,
  top: `13px`
});

const Info4 = styled("div")({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px 0px 24px 0px`,
  boxSizing: `border-box`,
  flex: `1`,
  margin: `0px 0px 0px 16px`,
  overflow: `hidden`
});

const YouGetPoints = styled("div")(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(34, 65, 58, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `500`,
  fontSize: `14px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  alignSelf: `stretch`,
  margin: `0px`
}));

const Q200Points = styled("div")(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(150, 198, 187, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `400`,
  fontSize: `12px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  alignSelf: `stretch`,
  margin: `6px 0px 0px 0px`
}));

function Timeline(props) {
  return (
    <Timeline1 className={props.className} style={{ marginLeft: "12px" }}>
      {props.date[0] !== undefined && (
        <ShippingInformation>
          <Timestamp>
            <Q0320>{props.date[0]}</Q0320>
            <Q1030>{props.time[0]}</Q1030>
          </Timestamp>
          <Line>
            <Rectangle688></Rectangle688>
            <Frame1373>
              <Ellipse63
                src={Ellipse63Image}
                loading="lazy"
                alt={"Ellipse 63"}
              />
              <Frame1398>
                <Group116>
                  <Rectangle693
                    src={Rectangle693Image}
                    loading="lazy"
                    alt={"Rectangle 693"}
                  />
                  <Rectangle694
                    src={Rectangle694Image}
                    loading="lazy"
                    alt={"Rectangle 694"}
                  />
                  <Rectangle695
                    src={Rectangle695Image}
                    loading="lazy"
                    alt={"Rectangle 695"}
                  />
                </Group116>
              </Frame1398>
            </Frame1373>
          </Line>
          <Info>
            <SeeYourRequest>{`See your request`}</SeeYourRequest>
            <YourRequestedIsBeing>{`Please wait a moment`}</YourRequestedIsBeing>
          </Info>
        </ShippingInformation>
      )}
      {props.date[1] !== undefined && (
        <ShippingInformation1>
          <Timestamp1>
            <Q03201>{props.date[1]}</Q03201>
            <Q1031>{props.time[1]}</Q1031>
          </Timestamp1>
          <Line1>
            <Frame1372>
              <Ellipse631
                src={Ellipse631Image}
                loading="lazy"
                alt={"Ellipse 63"}
              />
            </Frame1372>
            <Rectangle6881></Rectangle6881>
          </Line1>
          <Info1>
            <Received>{`Received`}</Received>
            <YourRequestHasBeenRe>
              {`Your request has been received`}
            </YourRequestHasBeenRe>
          </Info1>
        </ShippingInformation1>
      )}
      {props.date[2] !== undefined && (
        <ShippingInformation2>
          <Timestamp2>
            <Q03202>{props.date[2]}</Q03202>
            <Q1033>{props.time[2]}</Q1033>
          </Timestamp2>
          <Line2>
            <Frame13721>
              <Ellipse632
                src={Ellipse632Image}
                loading="lazy"
                alt={"Ellipse 63"}
              />
            </Frame13721>
            <Rectangle6882></Rectangle6882>
          </Line2>
          <Info2>
            <OnTheWay>{`On the way`}</OnTheWay>
            <WeAreOnOurWayToYourP>
              {`We are on our way to your place`}
            </WeAreOnOurWayToYourP>
          </Info2>
        </ShippingInformation2>
      )}
      {props.date[3] !== undefined && (
        <ShippingInformation3>
          <Timestamp3>
            <Q03203>{props.date[3]}</Q03203>
            <Q1044>{props.time[3]}</Q1044>
          </Timestamp3>
          <Line3>
            <Frame13722>
              <Ellipse633
                src={Ellipse633Image}
                loading="lazy"
                alt={"Ellipse 63"}
              />
            </Frame13722>
            <Rectangle6883></Rectangle6883>
          </Line3>
          <Info3>
            <HasArrived>{`Has arrived`}</HasArrived>
            <WeHaveArrivedAtYourP>
              {`We have arrived at your place`}
            </WeHaveArrivedAtYourP>
          </Info3>
        </ShippingInformation3>
      )}
      {props.date[4] !== undefined && (
        <ShippingInformation4>
          <Timestamp4>
            <Q03204>{props.date[4]}</Q03204>
            <Q1117>{props.time[4]}</Q1117>
          </Timestamp4>
          <Line4>
            <Frame13723>
              <Ellipse634
                src={Ellipse634Image}
                loading="lazy"
                alt={"Ellipse 63"}
              />
            </Frame13723>
            {false && <Rectangle6884></Rectangle6884>}
          </Line4>
          <Info4>
            <YouGetPoints>{`You get points`}</YouGetPoints>
            <Q200Points>{`+200 points`}</Q200Points>
          </Info4>
        </ShippingInformation4>
      )}
    </Timeline1>
  );
}

export default Timeline;
