/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preseve that abilty, always export from Quest to regenerate this file.
 *   To setup props, bindings and actions, use the Quest editor
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from "react";
import Ellipse66Image from "./../assets/images/TopUsers_Ellipse_66.png";
import MaskGroupImage from "./../assets/images/TopUsers_Mask_group.png";
import Ellipse67Image from "./../assets/images/TopUsers_Ellipse_67.png";
import Ellipse64Image from "./../assets/images/TopUsers_Ellipse_64.png";
import MaskGroup1Image from "./../assets/images/TopUsers_Mask_group_1.png";
import Ellipse671Image from "./../assets/images/TopUsers_Ellipse_67_1.png";
import Ellipse65Image from "./../assets/images/TopUsers_Ellipse_65.png";
import MaskGroup2Image from "./../assets/images/TopUsers_Mask_group_2.png";
import Ellipse672Image from "./../assets/images/TopUsers_Ellipse_67_2.png";
import { styled } from "@mui/material/styles";

const TopUsers1 = styled("div")({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  width: "100%",
  justifyContent: `space-between`,
  alignItems: `flex-end`,
  padding: `0px`,
  boxSizing: `border-box`,
  height: "auto"
});

const Group108 = styled("div")({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `91px`,
  height: `138px`
});

const Group105 = styled("div")({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `91px`,
  height: `39px`,
  left: `0px`,
  top: `99px`
});

const EmmaSmith = styled("div")(({ theme }) => ({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(34, 65, 58, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `500`,
  fontSize: `14px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `0px`,
  top: `0px`
}));

const Q7350 = styled("div")(({ theme }) => ({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(112, 138, 132, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `400`,
  fontSize: `12px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `31px`,
  top: `21px`
}));

const Group102 = styled("div")({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `75px`,
  height: `90px`,
  left: `7px`,
  top: `0px`
});

const Group99 = styled("div")({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `75px`,
  height: `75px`,
  left: `0px`,
  top: `0px`
});

const Ellipse66 = styled("img")({
  height: `75px`,
  width: `75px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`
});

const MaskGroup = styled("img")({
  height: `75px`,
  width: `75px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`
});

const Group90 = styled("div")({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `30px`,
  height: `30px`,
  left: `23px`,
  top: `60px`
});

const Ellipse67 = styled("img")({
  height: `30px`,
  width: `30px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`
});

const Q2 = styled("div")({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `600`,
  fontSize: `14px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `11px`,
  top: `5px`
});

const Group109 = styled("div")({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `116px`,
  height: `179px`
});

const Group106 = styled("div")({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `82px`,
  height: `39px`,
  left: `16px`,
  top: `140px`
});

const LucasMiller = styled("div")(({ theme }) => ({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(34, 65, 58, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `500`,
  fontSize: `14px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `0px`,
  top: `0px`
}));

const Q7981 = styled("div")(({ theme }) => ({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(112, 138, 132, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `400`,
  fontSize: `12px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `28px`,
  top: `21px`
}));

const Group103 = styled("div")({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `116px`,
  height: `131px`,
  left: `0px`,
  top: `0px`
});

const Group100 = styled("div")({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `116px`,
  height: `116px`,
  left: `0px`,
  top: `0px`
});

const Ellipse64 = styled("img")({
  height: `116px`,
  width: `116px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`
});

const MaskGroup1 = styled("img")({
  height: `116px`,
  width: `116px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`
});

const Group88 = styled("div")({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `30px`,
  height: `30px`,
  left: `43px`,
  top: `101px`
});

const Ellipse671 = styled("img")({
  height: `30px`,
  width: `30px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`
});

const Q1 = styled("div")({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `600`,
  fontSize: `14px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `12px`,
  top: `5px`
});

const Group110 = styled("div")({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `84px`,
  height: `138px`
});

const Group107 = styled("div")({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `84px`,
  height: `39px`,
  left: `0px`,
  top: `99px`
});

const NoahJones = styled("div")(({ theme }) => ({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(34, 65, 58, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `500`,
  fontSize: `14px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `0px`,
  top: `0px`
}));

const Q6744 = styled("div")(({ theme }) => ({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(112, 138, 132, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `400`,
  fontSize: `12px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `27px`,
  top: `21px`
}));

const Group104 = styled("div")({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `75px`,
  height: `90px`,
  left: `4px`,
  top: `0px`
});

const Group101 = styled("div")({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `75px`,
  height: `75px`,
  left: `0px`,
  top: `0px`
});

const Ellipse65 = styled("img")({
  height: `75px`,
  width: `75px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`
});

const MaskGroup2 = styled("img")({
  height: `75px`,
  width: `75px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`
});

const Group89 = styled("div")({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `30px`,
  height: `30px`,
  left: `23px`,
  top: `60px`
});

const Ellipse672 = styled("img")({
  height: `30px`,
  width: `30px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`
});

const Q3 = styled("div")({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `600`,
  fontSize: `14px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `11px`,
  top: `5px`
});

function TopUsers(props) {
  return (
    <TopUsers1 className={props.className}>
      <Group108>
        <Group105>
          <EmmaSmith>{`Emma Smith`}</EmmaSmith>
          <Q7350>{`7350`}</Q7350>
        </Group105>
        <Group102>
          <Group99>
            <Ellipse66 src={Ellipse66Image} loading="lazy" alt={"Ellipse 66"} />
            <MaskGroup src={MaskGroupImage} loading="lazy" alt={"Mask group"} />
          </Group99>
          <Group90>
            <Ellipse67 src={Ellipse67Image} loading="lazy" alt={"Ellipse 67"} />
            <Q2>{`2`}</Q2>
          </Group90>
        </Group102>
      </Group108>
      <Group109>
        <Group106>
          <LucasMiller>{`Lucas Miller`}</LucasMiller>
          <Q7981>{`7981`}</Q7981>
        </Group106>
        <Group103>
          <Group100>
            <Ellipse64 src={Ellipse64Image} loading="lazy" alt={"Ellipse 64"} />
            <MaskGroup1
              src={MaskGroup1Image}
              loading="lazy"
              alt={"Mask group"}
            />
          </Group100>
          <Group88>
            <Ellipse671
              src={Ellipse671Image}
              loading="lazy"
              alt={"Ellipse 67"}
            />
            <Q1>{`1`}</Q1>
          </Group88>
        </Group103>
      </Group109>
      <Group110>
        <Group107>
          <NoahJones>{`Noah Jones`}</NoahJones>
          <Q6744>{`6744`}</Q6744>
        </Group107>
        <Group104>
          <Group101>
            <Ellipse65 src={Ellipse65Image} loading="lazy" alt={"Ellipse 65"} />
            <MaskGroup2
              src={MaskGroup2Image}
              loading="lazy"
              alt={"Mask group"}
            />
          </Group101>
          <Group89>
            <Ellipse672
              src={Ellipse672Image}
              loading="lazy"
              alt={"Ellipse 67"}
            />
            <Q3>{`3`}</Q3>
          </Group89>
        </Group104>
      </Group110>
    </TopUsers1>
  );
}

export default TopUsers;
