/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preseve that abilty, always export from Quest to regenerate this file.
 *   To setup props, bindings and actions, use the Quest editor
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from "react";
import MaskGroupImage from "./../assets/images/Users_Mask_group.png";
import MaskGroup1Image from "./../assets/images/Users_Mask_group_1.png";
import MaskGroup2Image from "./../assets/images/Users_Mask_group_2.png";
import MaskGroup3Image from "./../assets/images/Users_Mask_group_3.png";
import MaskGroup4Image from "./../assets/images/Users_Mask_group_4.png";
import MaskGroup5Image from "./../assets/images/Users_Mask_group_5.png";
import MaskGroup6Image from "./../assets/images/Users_Mask_group_6.png";
import MaskGroup7Image from "./../assets/images/Users_Mask_group_7.png";
import MaskGroup8Image from "./../assets/images/Users_Mask_group_8.png";
import MaskGroup9Image from "./../assets/images/Users_Mask_group_9.png";
import MaskGroup10Image from "./../assets/images/Users_Mask_group_10.png";
import MaskGroup11Image from "./../assets/images/Users_Mask_group_11.png";
import { styled } from "@mui/material/styles";

const Users1 = styled("div")({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  width: "100%",
  height: `776px`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`
});

const Frame1383 = styled("div")({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `space-between`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `100%`,
  left: `0px`,
  top: `0px`
});

const Frame1382 = styled("div")({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `166px`,
  height: `50px`
});

const Group92 = styled("div")({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `104px`,
  height: `39px`,
  left: `62px`,
  top: `6px`
});

const OliviaJohnson = styled("div")(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(34, 65, 58, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `500`,
  fontSize: `14px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `0px`,
  top: `0px`
}));

const Q6702 = styled("div")(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(112, 138, 132, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `400`,
  fontSize: `12px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `0px`,
  top: `21px`
}));

const MaskGroup = styled("img")({
  height: `50px`,
  width: `50px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`
});

const Frame1381 = styled("div")({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `center`,
  alignItems: `center`,
  padding: `4px 12px`,
  boxSizing: `border-box`,
  overflow: `hidden`
});

const Q4 = styled("div")(({ theme }) => ({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(1, 152, 117, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `500`,
  fontSize: `12px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  margin: `0px`
}));

const Frame1384 = styled("div")({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `space-between`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `100%`,
  left: `0px`,
  top: `66px`
});

const Frame13821 = styled("div")({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `166px`,
  height: `50px`
});

const Group921 = styled("div")({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `75px`,
  height: `39px`,
  left: `62px`,
  top: `6px`
});

const AvaBrown = styled("div")(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(34, 65, 58, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `500`,
  fontSize: `14px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `0px`,
  top: `0px`
}));

const Q6647 = styled("div")(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(112, 138, 132, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `400`,
  fontSize: `12px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `0px`,
  top: `21px`
}));

const MaskGroup1 = styled("img")({
  height: `50px`,
  width: `50px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`
});

const Frame13811 = styled("div")({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `center`,
  alignItems: `center`,
  padding: `4px 12px`,
  boxSizing: `border-box`,
  overflow: `hidden`
});

const Q5 = styled("div")(({ theme }) => ({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(1, 152, 117, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `500`,
  fontSize: `12px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  margin: `0px`
}));

const Frame1385 = styled("div")({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `space-between`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `100%`,
  left: `0px`,
  top: `132px`
});

const Frame13822 = styled("div")({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `166px`,
  height: `50px`
});

const Group922 = styled("div")({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `98px`,
  height: `39px`,
  left: `62px`,
  top: `6px`
});

const LiamWilliams = styled("div")(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(34, 65, 58, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `500`,
  fontSize: `14px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `0px`,
  top: `0px`
}));

const Q6513 = styled("div")(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(112, 138, 132, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `400`,
  fontSize: `12px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `0px`,
  top: `21px`
}));

const MaskGroup2 = styled("img")({
  height: `50px`,
  width: `50px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`
});

const Frame13812 = styled("div")({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `center`,
  alignItems: `center`,
  padding: `4px 12px`,
  boxSizing: `border-box`,
  overflow: `hidden`
});

const Q6 = styled("div")(({ theme }) => ({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(1, 152, 117, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `500`,
  fontSize: `12px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  margin: `0px`
}));

const Frame1386 = styled("div")({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `space-between`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `100%`,
  left: `0px`,
  top: `198px`
});

const Frame13823 = styled("div")({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `166px`,
  height: `50px`
});

const Group923 = styled("div")({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `92px`,
  height: `39px`,
  left: `62px`,
  top: `6px`
});

const SophiaDavis = styled("div")(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(34, 65, 58, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `500`,
  fontSize: `14px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `0px`,
  top: `0px`
}));

const Q6490 = styled("div")(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(112, 138, 132, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `400`,
  fontSize: `12px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `0px`,
  top: `21px`
}));

const MaskGroup3 = styled("img")({
  height: `50px`,
  width: `50px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`
});

const Frame13813 = styled("div")({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `center`,
  alignItems: `center`,
  padding: `4px 12px`,
  boxSizing: `border-box`,
  overflow: `hidden`
});

const Q7 = styled("div")(({ theme }) => ({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(1, 152, 117, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `500`,
  fontSize: `12px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  margin: `0px`
}));

const Frame1387 = styled("div")({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `space-between`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `100%`,
  left: `0px`,
  top: `264px`
});

const Frame13824 = styled("div")({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `166px`,
  height: `50px`
});

const Group924 = styled("div")({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `91px`,
  height: `39px`,
  left: `62px`,
  top: `6px`
});

const EthanWilson = styled("div")(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(34, 65, 58, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `500`,
  fontSize: `14px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `0px`,
  top: `0px`
}));

const Q6421 = styled("div")(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(112, 138, 132, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `400`,
  fontSize: `12px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `0px`,
  top: `21px`
}));

const MaskGroup4 = styled("img")({
  height: `50px`,
  width: `50px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`
});

const Frame13814 = styled("div")({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `center`,
  alignItems: `center`,
  padding: `4px 12px`,
  boxSizing: `border-box`,
  overflow: `hidden`
});

const Q8 = styled("div")(({ theme }) => ({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(1, 152, 117, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `500`,
  fontSize: `12px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  margin: `0px`
}));

const Frame1388 = styled("div")({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `space-between`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `100%`,
  left: `0px`,
  top: `330px`
});

const Frame13825 = styled("div")({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `166px`,
  height: `50px`
});

const Group925 = styled("div")({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `103px`,
  height: `39px`,
  left: `62px`,
  top: `6px`
});

const IsabellaTaylor = styled("div")(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(34, 65, 58, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `500`,
  fontSize: `14px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `0px`,
  top: `0px`
}));

const Q6349 = styled("div")(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(112, 138, 132, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `400`,
  fontSize: `12px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `0px`,
  top: `21px`
}));

const MaskGroup5 = styled("img")({
  height: `50px`,
  width: `50px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`
});

const Frame13815 = styled("div")({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `center`,
  alignItems: `center`,
  padding: `4px 12px`,
  boxSizing: `border-box`,
  overflow: `hidden`
});

const Q9 = styled("div")(({ theme }) => ({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(1, 152, 117, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `500`,
  fontSize: `12px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  margin: `0px`
}));

const Frame1389 = styled("div")({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `space-between`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `100%`,
  left: `0px`,
  top: `396px`
});

const Frame13826 = styled("div")({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `166px`,
  height: `50px`
});

const Group926 = styled("div")({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `109px`,
  height: `39px`,
  left: `62px`,
  top: `6px`
});

const MasonThomas = styled("div")(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(34, 65, 58, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `500`,
  fontSize: `14px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `0px`,
  top: `0px`
}));

const Q6236 = styled("div")(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(112, 138, 132, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `400`,
  fontSize: `12px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `0px`,
  top: `21px`
}));

const MaskGroup6 = styled("img")({
  height: `50px`,
  width: `50px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`
});

const Frame13816 = styled("div")({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `center`,
  alignItems: `center`,
  padding: `4px 12px`,
  boxSizing: `border-box`,
  overflow: `hidden`
});

const Q10 = styled("div")(({ theme }) => ({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(1, 152, 117, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `500`,
  fontSize: `12px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  margin: `0px`
}));

const Frame1390 = styled("div")({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `space-between`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `100%`,
  left: `0px`,
  top: `462px`
});

const Frame13827 = styled("div")({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `166px`,
  height: `50px`
});

const Group927 = styled("div")({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `93px`,
  height: `39px`,
  left: `62px`,
  top: `6px`
});

const LoganMartin = styled("div")(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(34, 65, 58, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `500`,
  fontSize: `14px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `0px`,
  top: `0px`
}));

const Q5997 = styled("div")(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(112, 138, 132, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `400`,
  fontSize: `12px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `0px`,
  top: `21px`
}));

const MaskGroup7 = styled("img")({
  height: `50px`,
  width: `50px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`
});

const Frame13817 = styled("div")({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `center`,
  alignItems: `center`,
  padding: `4px 12px`,
  boxSizing: `border-box`,
  overflow: `hidden`
});

const Q11 = styled("div")(({ theme }) => ({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(1, 152, 117, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `500`,
  fontSize: `12px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  margin: `0px`
}));

const Frame1391 = styled("div")({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `space-between`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `100%`,
  left: `0px`,
  top: `528px`
});

const Frame13828 = styled("div")({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `166px`,
  height: `50px`
});

const Group928 = styled("div")({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `101px`,
  height: `39px`,
  left: `62px`,
  top: `6px`
});

const AmeliaGarcia = styled("div")(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(34, 65, 58, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `500`,
  fontSize: `14px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `0px`,
  top: `0px`
}));

const Q5613 = styled("div")(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(112, 138, 132, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `400`,
  fontSize: `12px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `0px`,
  top: `21px`
}));

const MaskGroup8 = styled("img")({
  height: `50px`,
  width: `50px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`
});

const Frame13818 = styled("div")({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `center`,
  alignItems: `center`,
  padding: `4px 12px`,
  boxSizing: `border-box`,
  overflow: `hidden`
});

const Q12 = styled("div")(({ theme }) => ({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(1, 152, 117, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `500`,
  fontSize: `12px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  margin: `0px`
}));

const Frame1392 = styled("div")({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `space-between`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `100%`,
  left: `0px`,
  top: `594px`
});

const Frame13829 = styled("div")({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `166px`,
  height: `50px`
});

const Group929 = styled("div")({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `116px`,
  height: `39px`,
  left: `62px`,
  top: `6px`
});

const JacobAnderson = styled("div")(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(34, 65, 58, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `500`,
  fontSize: `14px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `0px`,
  top: `0px`
}));

const Q5584 = styled("div")(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(112, 138, 132, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `400`,
  fontSize: `12px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `0px`,
  top: `21px`
}));

const MaskGroup9 = styled("img")({
  height: `50px`,
  width: `50px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`
});

const Frame13819 = styled("div")({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `center`,
  alignItems: `center`,
  padding: `4px 12px`,
  boxSizing: `border-box`,
  overflow: `hidden`
});

const Q13 = styled("div")(({ theme }) => ({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(1, 152, 117, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `500`,
  fontSize: `12px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  margin: `0px`
}));

const Frame1393 = styled("div")({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `space-between`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `100%`,
  left: `0px`,
  top: `660px`
});

const Frame138210 = styled("div")({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `166px`,
  height: `50px`
});

const Group9210 = styled("div")({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `95px`,
  height: `39px`,
  left: `62px`,
  top: `6px`
});

const AbigailHarris = styled("div")(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(34, 65, 58, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `500`,
  fontSize: `14px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `0px`,
  top: `0px`
}));

const Q5490 = styled("div")(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(112, 138, 132, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `400`,
  fontSize: `12px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `0px`,
  top: `21px`
}));

const MaskGroup10 = styled("img")({
  height: `50px`,
  width: `50px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`
});

const Frame138110 = styled("div")({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `center`,
  alignItems: `center`,
  padding: `4px 12px`,
  boxSizing: `border-box`,
  overflow: `hidden`
});

const Q14 = styled("div")(({ theme }) => ({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(1, 152, 117, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `500`,
  fontSize: `12px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  margin: `0px`
}));

const Frame1394 = styled("div")({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `space-between`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `100%`,
  left: `0px`,
  top: `726px`
});

const Frame138211 = styled("div")({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `166px`,
  height: `50px`
});

const Group9211 = styled("div")({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `80px`,
  height: `39px`,
  left: `62px`,
  top: `6px`
});

const HenryAllen = styled("div")(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(34, 65, 58, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `500`,
  fontSize: `14px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `0px`,
  top: `0px`
}));

const Q5177 = styled("div")(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(112, 138, 132, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `400`,
  fontSize: `12px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `0px`,
  top: `21px`
}));

const MaskGroup11 = styled("img")({
  height: `50px`,
  width: `50px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`
});

const Frame138111 = styled("div")({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `center`,
  alignItems: `center`,
  padding: `4px 12px`,
  boxSizing: `border-box`,
  overflow: `hidden`
});

const Q15 = styled("div")(({ theme }) => ({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(1, 152, 117, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `500`,
  fontSize: `12px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  margin: `0px`
}));

function Users(props) {
  return (
    <Users1 className={props.className}>
      <Frame1383>
        <Frame1382>
          <Group92>
            <OliviaJohnson>{`Olivia Johnson`}</OliviaJohnson>
            <Q6702>{`6702`}</Q6702>
          </Group92>
          <MaskGroup src={MaskGroupImage} loading="lazy" alt={"Mask group"} />
        </Frame1382>
        <Frame1381>
          <Q4>{`4`}</Q4>
        </Frame1381>
      </Frame1383>
      <Frame1384>
        <Frame13821>
          <Group921>
            <AvaBrown>{`Ava Brown`}</AvaBrown>
            <Q6647>{`6647`}</Q6647>
          </Group921>
          <MaskGroup1 src={MaskGroup1Image} loading="lazy" alt={"Mask group"} />
        </Frame13821>
        <Frame13811>
          <Q5>{`5`}</Q5>
        </Frame13811>
      </Frame1384>
      <Frame1385>
        <Frame13822>
          <Group922>
            <LiamWilliams>{`Liam Williams`}</LiamWilliams>
            <Q6513>{`6513`}</Q6513>
          </Group922>
          <MaskGroup2 src={MaskGroup2Image} loading="lazy" alt={"Mask group"} />
        </Frame13822>
        <Frame13812>
          <Q6>{`6`}</Q6>
        </Frame13812>
      </Frame1385>
      <Frame1386>
        <Frame13823>
          <Group923>
            <SophiaDavis>{`Sophia Davis`}</SophiaDavis>
            <Q6490>{`6490`}</Q6490>
          </Group923>
          <MaskGroup3 src={MaskGroup3Image} loading="lazy" alt={"Mask group"} />
        </Frame13823>
        <Frame13813>
          <Q7>{`7`}</Q7>
        </Frame13813>
      </Frame1386>
      <Frame1387>
        <Frame13824>
          <Group924>
            <EthanWilson>{`Ethan Wilson`}</EthanWilson>
            <Q6421>{`6421`}</Q6421>
          </Group924>
          <MaskGroup4 src={MaskGroup4Image} loading="lazy" alt={"Mask group"} />
        </Frame13824>
        <Frame13814>
          <Q8>{`8`}</Q8>
        </Frame13814>
      </Frame1387>
      <Frame1388>
        <Frame13825>
          <Group925>
            <IsabellaTaylor>{`Isabella Taylor`}</IsabellaTaylor>
            <Q6349>{`6349`}</Q6349>
          </Group925>
          <MaskGroup5 src={MaskGroup5Image} loading="lazy" alt={"Mask group"} />
        </Frame13825>
        <Frame13815>
          <Q9>{`9`}</Q9>
        </Frame13815>
      </Frame1388>
      <Frame1389>
        <Frame13826>
          <Group926>
            <MasonThomas>{`Mason Thomas`}</MasonThomas>
            <Q6236>{`6236`}</Q6236>
          </Group926>
          <MaskGroup6 src={MaskGroup6Image} loading="lazy" alt={"Mask group"} />
        </Frame13826>
        <Frame13816>
          <Q10>{`10`}</Q10>
        </Frame13816>
      </Frame1389>
      <Frame1390>
        <Frame13827>
          <Group927>
            <LoganMartin>{`Logan Martin`}</LoganMartin>
            <Q5997>{`5997`}</Q5997>
          </Group927>
          <MaskGroup7 src={MaskGroup7Image} loading="lazy" alt={"Mask group"} />
        </Frame13827>
        <Frame13817>
          <Q11>{`11`}</Q11>
        </Frame13817>
      </Frame1390>
      <Frame1391>
        <Frame13828>
          <Group928>
            <AmeliaGarcia>{`Amelia Garcia`}</AmeliaGarcia>
            <Q5613>{`5613`}</Q5613>
          </Group928>
          <MaskGroup8 src={MaskGroup8Image} loading="lazy" alt={"Mask group"} />
        </Frame13828>
        <Frame13818>
          <Q12>{`12`}</Q12>
        </Frame13818>
      </Frame1391>
      <Frame1392>
        <Frame13829>
          <Group929>
            <JacobAnderson>{`Jacob Anderson`}</JacobAnderson>
            <Q5584>{`5584`}</Q5584>
          </Group929>
          <MaskGroup9 src={MaskGroup9Image} loading="lazy" alt={"Mask group"} />
        </Frame13829>
        <Frame13819>
          <Q13>{`13`}</Q13>
        </Frame13819>
      </Frame1392>
      <Frame1393>
        <Frame138210>
          <Group9210>
            <AbigailHarris>{`Abigail Harris`}</AbigailHarris>
            <Q5490>{`5490`}</Q5490>
          </Group9210>
          <MaskGroup10
            src={MaskGroup10Image}
            loading="lazy"
            alt={"Mask group"}
          />
        </Frame138210>
        <Frame138110>
          <Q14>{`14`}</Q14>
        </Frame138110>
      </Frame1393>
      <Frame1394>
        <Frame138211>
          <Group9211>
            <HenryAllen>{`Henry Allen`}</HenryAllen>
            <Q5177>{`5177`}</Q5177>
          </Group9211>
          <MaskGroup11
            src={MaskGroup11Image}
            loading="lazy"
            alt={"Mask group"}
          />
        </Frame138211>
        <Frame138111>
          <Q15>{`15`}</Q15>
        </Frame138111>
      </Frame1394>
    </Users1>
  );
}

export default Users;
